# Práctica 2: Introducción a Numpy

**1.- Importar la biblioteca de NumPy.**

In [28]:
# Respuesta
import numpy as np

**2.- Crear un arreglo que contenga 10 ceros.**

In [29]:
# Respuesta
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**3.- Tomando en cuenta el arreglo anterior, modificar la dimensión para obtener un arreglo de 5 filas y 2 columnas.**

In [30]:
# Respuesta
a.reshape(5,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

**4.- Crear un arreglo que contenga 10 números uno.**

In [31]:
# Respuesta
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**5.- Crear un arreglo que contenga 10 números cinco.**

In [32]:
# Respuesta 
c=b*5
c

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**6.- Obtener un arreglo donde sus elementos sean números enteros entre 10 y 50, considerando un salto unitario.**

In [33]:
# Respuesta
d = np.arange(10,51,1)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**7.- Generar un arreglo con todos los números pares entre 10 y 50.**

In [34]:
# Respuesta
e = np.arange(10,51,2)
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**8.- Crear una matriz identidad de 3x3.**

In [46]:
# Respuesta
f = np.identity(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
m=np.zeros(9).reshape(3,3)
for i in range(3):
  m[i][i]=1
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**9.- Generar dos números aleatorios entre 0 y 1.** 

In [66]:
# Respuesta
np.random.rand(2)

array([0.8811032 , 0.58127287])

**10.- Obtener una muestra de 12 valores que provengan de una distribución $N(0,1)$.**

In [65]:
# Respuesta
np.random.randn(1,12)

array([[-1.16514984,  0.90082649,  0.46566244, -1.53624369,  1.48825219,
         1.89588918,  1.17877957, -0.17992484, -1.07075262,  1.05445173,
        -0.40317695,  1.22244507]])

**11.- ¿De qué forma podría obtener siempre el mismo valor cuando uso funciones que generan números aleatorios?** 

In [38]:
# Respuesta
np.random.seed(0)

**12.- Genera exactamente la sigueinte matriz sin tener que ingresar los datos de forma "manual".**

  $\begin{pmatrix}
  0.01 & 0.02 & 0.03\\ 
  0.04 & 0.05 & 0.06\\
  0.07 & 0.08 & 0.09
\end{pmatrix}$ 


In [74]:
# Respuesta
g=np.arange(1,10)/100
g.reshape(3,3)

array([[0.01, 0.02, 0.03],
       [0.04, 0.05, 0.06],
       [0.07, 0.08, 0.09]])

**13.- Crear un arreglo con 20 puntos seperados uniformemente entre 0 y 1.**

In [76]:
# Respuesta
h = np.linspace(0,1,20)
h

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**14.- Considerando la siguiente matriz:**

  $\begin{pmatrix}
  1 & 2 & 3 & 4 & 5\\ 
  6 & 7 & 8 & 9 & 10\\
  11 & 12 & 13 & 14 & 15\\
  16 & 17 & 18 & 19 & 20\\
  21 & 22 & 23 & 24 & 25
\end{pmatrix}$ 

**a) Extraer:**

  $\begin{pmatrix}
  12 & 13 & 14 & 15\\
  17 & 18 & 19 & 20\\
  22 & 23 & 24 & 25
\end{pmatrix}$ 


In [111]:
# Respuesta
j = np.arange(1,26,1).reshape(5,5)
print(j[2:, 1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


**b) Extraer el valor de 14**

In [84]:
# Respuesta
j[2][3]

14

**c) Extraer el siguiente arreglo:**

  $\begin{pmatrix}
  2\\ 
  7\\
  12
\end{pmatrix}$ 

In [117]:
print(j[0:3,1:2])

[[ 2]
 [ 7]
 [12]]


**15.- Sumar todos los valores del arreglo del ejercicio 14.**

In [92]:
# Respuesta
j.sum()

325

**16.- Calcular la desviación estándar del arreglo en el ejercicio 14.**

In [93]:
# Respuesta
j.std()

7.211102550927978